/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/avatar.glb -o src/components/Avatar.jsx -k -r public 
*/

import React, {useEffect, useRef, useState} from 'react'
import {useFrame, useGraph} from '@react-three/fiber'
import {useGLTF, useAnimations, useFBX, useScroll} from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from "three";

export function Avatar(props) {
  const group = React.useRef()
  const { scene } = useGLTF('/models/avatar.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  const {animations: idleAnimation} = useFBX('animations/Idle.fbx');
  const {animations: walkingAnimation} = useFBX('animations/Walking.fbx');

  idleAnimation[0].name = 'Idle'
  walkingAnimation[0].name = 'Walking'

  const animations = [ idleAnimation[0], walkingAnimation[0]]
  const { actions } = useAnimations(animations, group)

  const [animation, setAnimation] = useState('Idle');
  useEffect(() => {
    const action = actions?.[animation]
    action?.reset().fadeIn(1).play()

    return () => {
      action?.fadeOut(1)
    }
  }, [animation, actions])

  const scrollData= useScroll()
  const lastScroll = useRef(0);
  useFrame(() => {
    const scrollDelta = scrollData.offset - lastScroll.current;
    let rotationTarget = 0;
    if(Math.abs(scrollDelta) > 0.00001) {
      setAnimation('Walking');
      if(scrollDelta > 0) {
        rotationTarget = 0;
      } else {
        rotationTarget = Math.PI;
      }
    } else {
      setAnimation('Idle');
    }
    group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, rotationTarget, 0.1);
    lastScroll.current = scrollData.offset;
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips} />
          <skinnedMesh name="avaturn_body" geometry={nodes.avaturn_body.geometry} material={materials.avaturn_body_material} skeleton={nodes.avaturn_body.skeleton} />
          <skinnedMesh name="avaturn_hair_0" geometry={nodes.avaturn_hair_0.geometry} material={materials.avaturn_hair_0_material} skeleton={nodes.avaturn_hair_0.skeleton} />
          <skinnedMesh name="avaturn_hair_1" geometry={nodes.avaturn_hair_1.geometry} material={materials.avaturn_hair_1_material} skeleton={nodes.avaturn_hair_1.skeleton} />
          <skinnedMesh name="avaturn_shoes_0" geometry={nodes.avaturn_shoes_0.geometry} material={materials.avaturn_shoes_0_material} skeleton={nodes.avaturn_shoes_0.skeleton} />
          <skinnedMesh name="avaturn_look_0" geometry={nodes.avaturn_look_0.geometry} material={materials.avaturn_look_0_material} skeleton={nodes.avaturn_look_0.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/avatar.glb')
useFBX.preload('animations/Idle.fbx');
useFBX.preload('animations/Walking.fbx');